server:
  port: 6080

---
spring:
  application:
    name: id-generator

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idgenerator
    username: root
    password: root

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

---
id:
  generator:
    repository: mysql
    one-request-id-max: 50
